package local

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/ambientlabscomputing/underleaf_client/internal/commands/utils"
	"github.com/ambientlabscomputing/underleaf_client/internal/crypto"
	"github.com/ambientlabscomputing/underleaf_client/internal/policy_manager"
	"github.com/spf13/cobra"
)

// SubmitCSRCmd submits a CSR to the control plane for signing
var SubmitCSRCmd = &cobra.Command{
	Use:   "submit",
	Short: "Submit Certificate Signing Request to server API",
	Long: `Submit a CSR (Certificate Signing Request) to the server API for signing.
This command reads the CSR generated by 'ufctl csr generate' and submits
it to the control plane API. The signed certificate is saved locally and can
be used for mTLS authentication.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		deps := utils.NewDependencyManager(ctx)

		deps.Printer.PrintInfo("=== Submit Certificate Signing Request ===\n")
		deps.Printer.PrintInfo("Submitting CSR to server API for signing...\n")

		// Get server ID from config
		serverIDRaw, ok := deps.ConfigClient.Get("local.server_id")
		if !ok || serverIDRaw == nil {
			deps.Printer.PrintError("Server not registered. Please run 'ufctl start' first.")
			return fmt.Errorf("server not registered")
		}

		serverID, ok := serverIDRaw.(string)
		if !ok || serverID == "" {
			deps.Printer.PrintError("Invalid server ID in config")
			return fmt.Errorf("invalid server ID")
		}

		// Get certificate paths
		basePath := policy_manager.GetBasePath(false)
		keyPath, csrPath, certPath := crypto.GetCertPaths(basePath, serverID)

		// Check if CSR exists
		if _, err := os.Stat(csrPath); os.IsNotExist(err) {
			deps.Printer.PrintError(fmt.Sprintf("CSR file not found at: %s", csrPath))
			deps.Printer.PrintError("Please run 'ufctl csr generate' first.")
			return fmt.Errorf("CSR not found")
		}

		// Read CSR file
		csrPEM, err := os.ReadFile(csrPath)
		if err != nil {
			deps.Printer.PrintError("Failed to read CSR file.")
			return fmt.Errorf("failed to read CSR: %w", err)
		}

		deps.Printer.PrintSuccess(fmt.Sprintf("CSR loaded from: %s", csrPath))

		// Get API base URL
		baseURL, ok := deps.ConfigClient.Get("api.base_url")
		if !ok || baseURL == nil {
			deps.Printer.PrintError("API base URL not configured.")
			return fmt.Errorf("api.base_url not configured")
		}

		// Get auth token
		token, ok := deps.ConfigClient.Get("auth.token")
		if !ok || token == nil {
			deps.Printer.PrintError("Not authenticated. Please run 'ufctl auth login' first.")
			return fmt.Errorf("auth token not found")
		}

		// Submit CSR to API
		endpoint := fmt.Sprintf("%s/servers/%s/csr", baseURL.(string), serverID)
		deps.Printer.PrintInfo(fmt.Sprintf("Submitting CSR to: %s\n", endpoint))

		// Make HTTP request
		client := &http.Client{Timeout: 30 * time.Second}
		req, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewReader(csrPEM))
		if err != nil {
			deps.Printer.PrintError("Failed to create request.")
			return fmt.Errorf("failed to create request: %w", err)
		}

		req.Header.Set("Authorization", "Bearer "+token.(string))
		req.Header.Set("Content-Type", "text/plain")

		// Add organization context if available
		if orgID, ok := deps.ConfigClient.Get("local.organization_id"); ok && orgID != nil && orgID != "" {
			req.Header.Set("X-Organization-ID", orgID.(string))
		}

		resp, err := client.Do(req)
		if err != nil {
			deps.Printer.PrintError("Failed to submit CSR.")
			return fmt.Errorf("failed to submit CSR: %w", err)
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			bodyBytes, _ := io.ReadAll(resp.Body)
			deps.Printer.PrintError(fmt.Sprintf("API request failed with status %d", resp.StatusCode))
			deps.Printer.PrintError(string(bodyBytes))
			return fmt.Errorf("API request failed with status %d", resp.StatusCode)
		}

		// Read signed certificate
		certPEM, err := io.ReadAll(resp.Body)
		if err != nil {
			deps.Printer.PrintError("Failed to read signed certificate.")
			return fmt.Errorf("failed to read certificate: %w", err)
		}

		// Save certificate to file
		err = os.WriteFile(certPath, certPEM, 0644)
		if err != nil {
			deps.Printer.PrintError("Failed to save certificate.")
			return fmt.Errorf("failed to save certificate: %w", err)
		}

		deps.Printer.PrintSuccess(fmt.Sprintf("Certificate saved to: %s", certPath))

		// Update config with certificate and key paths
		deps.ConfigClient.Set("local.mtls.certificate_path", certPath)
		deps.ConfigClient.Set("local.mtls.private_key_path", keyPath)

		deps.Printer.PrintSuccess("\n✓ Certificate successfully signed and saved!")
		deps.Printer.PrintInfo("\nNext steps:")
		deps.Printer.PrintInfo("1. The agent will automatically use this certificate for mTLS authentication")
		deps.Printer.PrintInfo("2. Restart the agent to begin using mTLS: ufctl agent start")

		return nil
	},
}
