// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/raft/proto/raft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogType represents the type of log entry.
type LogType int32

const (
	// LOG_COMMAND is a normal command.
	LogType_LOG_COMMAND LogType = 0
	// LOG_NOOP is a no-op entry (used for leadership assertion).
	LogType_LOG_NOOP LogType = 1
	// LOG_ADD_PEER adds a peer.
	LogType_LOG_ADD_PEER LogType = 2
	// LOG_REMOVE_PEER removes a peer.
	LogType_LOG_REMOVE_PEER LogType = 3
	// LOG_BARRIER is a barrier.
	LogType_LOG_BARRIER LogType = 4
	// LOG_CONFIGURATION is a configuration change.
	LogType_LOG_CONFIGURATION LogType = 5
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_COMMAND",
		1: "LOG_NOOP",
		2: "LOG_ADD_PEER",
		3: "LOG_REMOVE_PEER",
		4: "LOG_BARRIER",
		5: "LOG_CONFIGURATION",
	}
	LogType_value = map[string]int32{
		"LOG_COMMAND":       0,
		"LOG_NOOP":          1,
		"LOG_ADD_PEER":      2,
		"LOG_REMOVE_PEER":   3,
		"LOG_BARRIER":       4,
		"LOG_CONFIGURATION": 5,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_raft_proto_raft_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_internal_raft_proto_raft_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{0}
}

// AppendEntriesRequest is sent by the leader to replicate log entries and heartbeat.
type AppendEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the leader's term.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Leader is the leader's address.
	Leader []byte `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// PrevLogEntry is the index of the log entry immediately preceding new ones.
	PrevLogEntry uint64 `protobuf:"varint,3,opt,name=prev_log_entry,json=prevLogEntry,proto3" json:"prev_log_entry,omitempty"`
	// PrevLogTerm is the term of prev_log_entry.
	PrevLogTerm uint64 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	// Entries are log entries to store (empty for heartbeat).
	Entries []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	// LeaderCommitIndex is the leader's commit index.
	LeaderCommitIndex uint64 `protobuf:"varint,6,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *AppendEntriesRequest) GetPrevLogEntry() uint64 {
	if x != nil {
		return x.PrevLogEntry
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommitIndex() uint64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

// AppendEntriesResponse is the response to AppendEntriesRequest.
type AppendEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the current term, for leader to update itself.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// LastLog is the index of the last log entry.
	LastLog uint64 `protobuf:"varint,2,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	// Success is true if follower contained entry matching prev_log_entry and prev_log_term.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// NoRetryBackoff is true if the follower doesn't want to retry immediately.
	NoRetryBackoff bool `protobuf:"varint,4,opt,name=no_retry_backoff,json=noRetryBackoff,proto3" json:"no_retry_backoff,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetLastLog() uint64 {
	if x != nil {
		return x.LastLog
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetNoRetryBackoff() bool {
	if x != nil {
		return x.NoRetryBackoff
	}
	return false
}

// RequestVoteRequest is sent by candidates to gather votes.
type RequestVoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the candidate's term.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Candidate is the candidate requesting vote.
	Candidate []byte `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	// LastLogIndex is the index of candidate's last log entry.
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	// LastLogTerm is the term of candidate's last log entry.
	LastLogTerm uint64 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// LeadershipTransfer indicates if this is part of a leadership transfer.
	LeadershipTransfer bool `protobuf:"varint,5,opt,name=leadership_transfer,json=leadershipTransfer,proto3" json:"leadership_transfer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidate() []byte {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetLeadershipTransfer() bool {
	if x != nil {
		return x.LeadershipTransfer
	}
	return false
}

// RequestVoteResponse is the response to RequestVoteRequest.
type RequestVoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the current term, for candidate to update itself.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Granted is true if the candidate received the vote.
	Granted       bool `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

// InstallSnapshotRequest is sent by the leader to send a snapshot to a follower.
type InstallSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the leader's term.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Leader is the leader's address.
	Leader []byte `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// LastLogIndex is the snapshot's last included index.
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	// LastLogTerm is the snapshot's last included term.
	LastLogTerm uint64 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// Configuration is the cluster configuration at last_log_index.
	Configuration []byte `protobuf:"bytes,5,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// ConfigurationIndex is the index of the configuration.
	ConfigurationIndex uint64 `protobuf:"varint,6,opt,name=configuration_index,json=configurationIndex,proto3" json:"configuration_index,omitempty"`
	// Size is the total size of the snapshot.
	Size int64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// Data is a chunk of snapshot data.
	Data          []byte `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *InstallSnapshotRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *InstallSnapshotRequest) GetConfigurationIndex() uint64 {
	if x != nil {
		return x.ConfigurationIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// InstallSnapshotResponse is the response to InstallSnapshotRequest.
type InstallSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term is the current term, for leader to update itself.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Success is true if the snapshot was successfully installed.
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TimeoutNowRequest triggers an immediate election timeout.
type TimeoutNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowRequest) Reset() {
	*x = TimeoutNowRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowRequest) ProtoMessage() {}

func (x *TimeoutNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowRequest.ProtoReflect.Descriptor instead.
func (*TimeoutNowRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{6}
}

// TimeoutNowResponse is the response to TimeoutNowRequest.
type TimeoutNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowResponse) Reset() {
	*x = TimeoutNowResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowResponse) ProtoMessage() {}

func (x *TimeoutNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowResponse.ProtoReflect.Descriptor instead.
func (*TimeoutNowResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{7}
}

// LogEntry represents a single entry in the Raft log.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index is the log entry index.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Term is the term when the entry was received.
	Term uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// Type is the log entry type.
	Type LogType `protobuf:"varint,3,opt,name=type,proto3,enum=raft.LogType" json:"type,omitempty"`
	// Data is the log entry data.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Extensions for protocol extensions (not used in base Raft).
	Extensions    []byte `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_COMMAND
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEntry) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_internal_raft_proto_raft_proto protoreflect.FileDescriptor

const file_internal_raft_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/raft/proto/raft.proto\x12\x04raft\"\xe6\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\fR\x06leader\x12$\n" +
	"\x0eprev_log_entry\x18\x03 \x01(\x04R\fprevLogEntry\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x05 \x03(\v2\x0e.raft.LogEntryR\aentries\x12.\n" +
	"\x13leader_commit_index\x18\x06 \x01(\x04R\x11leaderCommitIndex\"\x8a\x01\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x19\n" +
	"\blast_log\x18\x02 \x01(\x04R\alastLog\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12(\n" +
	"\x10no_retry_backoff\x18\x04 \x01(\bR\x0enoRetryBackoff\"\xc1\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\fR\tcandidate\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\x12/\n" +
	"\x13leadership_transfer\x18\x05 \x01(\bR\x12leadershipTransfer\"C\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\"\x8d\x02\n" +
	"\x16InstallSnapshotRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\fR\x06leader\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\x12$\n" +
	"\rconfiguration\x18\x05 \x01(\fR\rconfiguration\x12/\n" +
	"\x13configuration_index\x18\x06 \x01(\x04R\x12configurationIndex\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"G\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x13\n" +
	"\x11TimeoutNowRequest\"\x14\n" +
	"\x12TimeoutNowResponse\"\x8b\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12!\n" +
	"\x04type\x18\x03 \x01(\x0e2\r.raft.LogTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"extensions\x18\x05 \x01(\fR\n" +
	"extensions*w\n" +
	"\aLogType\x12\x0f\n" +
	"\vLOG_COMMAND\x10\x00\x12\f\n" +
	"\bLOG_NOOP\x10\x01\x12\x10\n" +
	"\fLOG_ADD_PEER\x10\x02\x12\x13\n" +
	"\x0fLOG_REMOVE_PEER\x10\x03\x12\x0f\n" +
	"\vLOG_BARRIER\x10\x04\x12\x15\n" +
	"\x11LOG_CONFIGURATION\x10\x052\xb0\x02\n" +
	"\rRaftTransport\x12H\n" +
	"\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12B\n" +
	"\vRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12P\n" +
	"\x0fInstallSnapshot\x12\x1c.raft.InstallSnapshotRequest\x1a\x1d.raft.InstallSnapshotResponse(\x01\x12?\n" +
	"\n" +
	"TimeoutNow\x12\x17.raft.TimeoutNowRequest\x1a\x18.raft.TimeoutNowResponseBFZDgithub.com/ambientlabscomputing/underleaf_client/internal/raft/protob\x06proto3"

var (
	file_internal_raft_proto_raft_proto_rawDescOnce sync.Once
	file_internal_raft_proto_raft_proto_rawDescData []byte
)

func file_internal_raft_proto_raft_proto_rawDescGZIP() []byte {
	file_internal_raft_proto_raft_proto_rawDescOnce.Do(func() {
		file_internal_raft_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_raft_proto_raft_proto_rawDesc), len(file_internal_raft_proto_raft_proto_rawDesc)))
	})
	return file_internal_raft_proto_raft_proto_rawDescData
}

var file_internal_raft_proto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_raft_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_raft_proto_raft_proto_goTypes = []any{
	(LogType)(0),                    // 0: raft.LogType
	(*AppendEntriesRequest)(nil),    // 1: raft.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 2: raft.AppendEntriesResponse
	(*RequestVoteRequest)(nil),      // 3: raft.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 4: raft.RequestVoteResponse
	(*InstallSnapshotRequest)(nil),  // 5: raft.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 6: raft.InstallSnapshotResponse
	(*TimeoutNowRequest)(nil),       // 7: raft.TimeoutNowRequest
	(*TimeoutNowResponse)(nil),      // 8: raft.TimeoutNowResponse
	(*LogEntry)(nil),                // 9: raft.LogEntry
}
var file_internal_raft_proto_raft_proto_depIdxs = []int32{
	9, // 0: raft.AppendEntriesRequest.entries:type_name -> raft.LogEntry
	0, // 1: raft.LogEntry.type:type_name -> raft.LogType
	1, // 2: raft.RaftTransport.AppendEntries:input_type -> raft.AppendEntriesRequest
	3, // 3: raft.RaftTransport.RequestVote:input_type -> raft.RequestVoteRequest
	5, // 4: raft.RaftTransport.InstallSnapshot:input_type -> raft.InstallSnapshotRequest
	7, // 5: raft.RaftTransport.TimeoutNow:input_type -> raft.TimeoutNowRequest
	2, // 6: raft.RaftTransport.AppendEntries:output_type -> raft.AppendEntriesResponse
	4, // 7: raft.RaftTransport.RequestVote:output_type -> raft.RequestVoteResponse
	6, // 8: raft.RaftTransport.InstallSnapshot:output_type -> raft.InstallSnapshotResponse
	8, // 9: raft.RaftTransport.TimeoutNow:output_type -> raft.TimeoutNowResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_raft_proto_raft_proto_init() }
func file_internal_raft_proto_raft_proto_init() {
	if File_internal_raft_proto_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_raft_proto_raft_proto_rawDesc), len(file_internal_raft_proto_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_raft_proto_raft_proto_goTypes,
		DependencyIndexes: file_internal_raft_proto_raft_proto_depIdxs,
		EnumInfos:         file_internal_raft_proto_raft_proto_enumTypes,
		MessageInfos:      file_internal_raft_proto_raft_proto_msgTypes,
	}.Build()
	File_internal_raft_proto_raft_proto = out.File
	file_internal_raft_proto_raft_proto_goTypes = nil
	file_internal_raft_proto_raft_proto_depIdxs = nil
}
