// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/ua_mma/v1/event_stream.proto

package ua_mmav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UAEventStreamService_StreamEvents_FullMethodName = "/ua_mma.v1.UAEventStreamService/StreamEvents"
)

// UAEventStreamServiceClient is the client API for UAEventStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UAEventStreamService provides a server-streaming RPC for the Underleaf Agent
// to publish membership, lifecycle, policy, and capability cache events to
// the Mycelium Mesh Agent.
//
// Interface Contract: §3 UA → MMA Event Stream
type UAEventStreamServiceClient interface {
	// StreamEvents establishes a server-side streaming RPC where the UA pushes
	// events to the MMA. The MMA provides last_seen_seq for resumption and can
	// optionally filter by event types.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UAEvent], error)
}

type uAEventStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUAEventStreamServiceClient(cc grpc.ClientConnInterface) UAEventStreamServiceClient {
	return &uAEventStreamServiceClient{cc}
}

func (c *uAEventStreamServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UAEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UAEventStreamService_ServiceDesc.Streams[0], UAEventStreamService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, UAEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UAEventStreamService_StreamEventsClient = grpc.ServerStreamingClient[UAEvent]

// UAEventStreamServiceServer is the server API for UAEventStreamService service.
// All implementations must embed UnimplementedUAEventStreamServiceServer
// for forward compatibility.
//
// UAEventStreamService provides a server-streaming RPC for the Underleaf Agent
// to publish membership, lifecycle, policy, and capability cache events to
// the Mycelium Mesh Agent.
//
// Interface Contract: §3 UA → MMA Event Stream
type UAEventStreamServiceServer interface {
	// StreamEvents establishes a server-side streaming RPC where the UA pushes
	// events to the MMA. The MMA provides last_seen_seq for resumption and can
	// optionally filter by event types.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[UAEvent]) error
	mustEmbedUnimplementedUAEventStreamServiceServer()
}

// UnimplementedUAEventStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUAEventStreamServiceServer struct{}

func (UnimplementedUAEventStreamServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[UAEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedUAEventStreamServiceServer) mustEmbedUnimplementedUAEventStreamServiceServer() {}
func (UnimplementedUAEventStreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeUAEventStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UAEventStreamServiceServer will
// result in compilation errors.
type UnsafeUAEventStreamServiceServer interface {
	mustEmbedUnimplementedUAEventStreamServiceServer()
}

func RegisterUAEventStreamServiceServer(s grpc.ServiceRegistrar, srv UAEventStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedUAEventStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UAEventStreamService_ServiceDesc, srv)
}

func _UAEventStreamService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UAEventStreamServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, UAEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UAEventStreamService_StreamEventsServer = grpc.ServerStreamingServer[UAEvent]

// UAEventStreamService_ServiceDesc is the grpc.ServiceDesc for UAEventStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UAEventStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_mma.v1.UAEventStreamService",
	HandlerType: (*UAEventStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _UAEventStreamService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ua_mma/v1/event_stream.proto",
}
