// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ua_mma/v1/event_stream.proto

package ua_mmav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamEventsRequest configures event stream subscription.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// last_seen_seq is a map of node_id → last sequence number seen by the MMA.
	// The UA uses this for catch-up: it will replay events from last_seen_seq+1
	// onwards per node, then stream live events.
	LastSeenSeq map[string]uint64 `protobuf:"bytes,1,rep,name=last_seen_seq,json=lastSeenSeq,proto3" json:"last_seen_seq,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// event_type_filter restricts which event types to receive. If empty, all
	// event types are streamed. Example values: "cluster.snapshot",
	// "service.started", "mesh_policy.updated".
	EventTypeFilter []string `protobuf:"bytes,2,rep,name=event_type_filter,json=eventTypeFilter,proto3" json:"event_type_filter,omitempty"`
	// buffer_size_hint suggests the per-subscriber buffer size on the UA side
	// (in number of events, not bytes). The UA may clamp this to its own limits.
	// Default: 1000 events.
	BufferSizeHint uint32 `protobuf:"varint,3,opt,name=buffer_size_hint,json=bufferSizeHint,proto3" json:"buffer_size_hint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ua_mma_v1_event_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEventsRequest) GetLastSeenSeq() map[string]uint64 {
	if x != nil {
		return x.LastSeenSeq
	}
	return nil
}

func (x *StreamEventsRequest) GetEventTypeFilter() []string {
	if x != nil {
		return x.EventTypeFilter
	}
	return nil
}

func (x *StreamEventsRequest) GetBufferSizeHint() uint32 {
	if x != nil {
		return x.BufferSizeHint
	}
	return 0
}

// UAEvent is the envelope for all UA→MMA events. The event_type field
// determines the structure of the payload.
//
// Interface Contract: §3.1 Event Envelope
type UAEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is globally unique (UUID/ULID).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// event_type determines the payload structure. Examples:
	//   - "cluster.snapshot"
	//   - "member.joined"
	//   - "member.updated"
	//   - "member.left"
	//   - "member.health"
	//   - "identity.trust_roots.updated"
	//   - "identity.service.issued"
	//   - "identity.service.revoked"
	//   - "service.started"
	//   - "service.updated"
	//   - "service.stopped"
	//   - "capability_cache.snapshot.updated"
	//   - "capability_cache.delta.updated"
	//   - "mesh_policy.updated"
	//   - "consent_state.updated"
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// emitted_at is the RFC3339 timestamp when the UA emitted the event.
	EmittedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	// cluster_id identifies the cluster.
	ClusterId string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// node_id is the origin node that emitted the event.
	NodeId string `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// seq is a monotonically increasing sequence number per node_id.
	// Used for ordering and catch-up (last_seen_seq).
	Seq uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	// entity_ref optionally identifies the entity this event concerns.
	EntityRef *EntityRef `protobuf:"bytes,7,opt,name=entity_ref,json=entityRef,proto3" json:"entity_ref,omitempty"`
	// payload contains the event-specific data as a flexible JSON-like structure.
	// The MMA unmarshals this based on event_type.
	Payload *structpb.Struct `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	// signature is an optional UA signature over the envelope+payload for
	// integrity verification. Format: base64-encoded ECDSA signature.
	Signature     string `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UAEvent) Reset() {
	*x = UAEvent{}
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UAEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UAEvent) ProtoMessage() {}

func (x *UAEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UAEvent.ProtoReflect.Descriptor instead.
func (*UAEvent) Descriptor() ([]byte, []int) {
	return file_proto_ua_mma_v1_event_stream_proto_rawDescGZIP(), []int{1}
}

func (x *UAEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UAEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UAEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *UAEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UAEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UAEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *UAEvent) GetEntityRef() *EntityRef {
	if x != nil {
		return x.EntityRef
	}
	return nil
}

func (x *UAEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UAEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// EntityRef identifies an entity (member, service, capability, policy).
type EntityRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the entity type: "member", "service", "capability", "policy", etc.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// id is the entity's unique identifier.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ua_mma_v1_event_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_proto_ua_mma_v1_event_stream_proto_rawDescGZIP(), []int{2}
}

func (x *EntityRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EntityRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_ua_mma_v1_event_stream_proto protoreflect.FileDescriptor

const file_proto_ua_mma_v1_event_stream_proto_rawDesc = "" +
	"\n" +
	"\"proto/ua_mma/v1/event_stream.proto\x12\tua_mma.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x13StreamEventsRequest\x12S\n" +
	"\rlast_seen_seq\x18\x01 \x03(\v2/.ua_mma.v1.StreamEventsRequest.LastSeenSeqEntryR\vlastSeenSeq\x12*\n" +
	"\x11event_type_filter\x18\x02 \x03(\tR\x0feventTypeFilter\x12(\n" +
	"\x10buffer_size_hint\x18\x03 \x01(\rR\x0ebufferSizeHint\x1a>\n" +
	"\x10LastSeenSeqEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xce\x02\n" +
	"\aUAEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x129\n" +
	"\n" +
	"emitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x123\n" +
	"\n" +
	"entity_ref\x18\a \x01(\v2\x14.ua_mma.v1.EntityRefR\tentityRef\x121\n" +
	"\apayload\x18\b \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\"/\n" +
	"\tEntityRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\\\n" +
	"\x14UAEventStreamService\x12D\n" +
	"\fStreamEvents\x12\x1e.ua_mma.v1.StreamEventsRequest\x1a\x12.ua_mma.v1.UAEvent0\x01BLZJgithub.com/AmbientLabs/underleaf/underleaf_client/proto/ua_mma/v1;ua_mmav1b\x06proto3"

var (
	file_proto_ua_mma_v1_event_stream_proto_rawDescOnce sync.Once
	file_proto_ua_mma_v1_event_stream_proto_rawDescData []byte
)

func file_proto_ua_mma_v1_event_stream_proto_rawDescGZIP() []byte {
	file_proto_ua_mma_v1_event_stream_proto_rawDescOnce.Do(func() {
		file_proto_ua_mma_v1_event_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ua_mma_v1_event_stream_proto_rawDesc), len(file_proto_ua_mma_v1_event_stream_proto_rawDesc)))
	})
	return file_proto_ua_mma_v1_event_stream_proto_rawDescData
}

var file_proto_ua_mma_v1_event_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ua_mma_v1_event_stream_proto_goTypes = []any{
	(*StreamEventsRequest)(nil),   // 0: ua_mma.v1.StreamEventsRequest
	(*UAEvent)(nil),               // 1: ua_mma.v1.UAEvent
	(*EntityRef)(nil),             // 2: ua_mma.v1.EntityRef
	nil,                           // 3: ua_mma.v1.StreamEventsRequest.LastSeenSeqEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_proto_ua_mma_v1_event_stream_proto_depIdxs = []int32{
	3, // 0: ua_mma.v1.StreamEventsRequest.last_seen_seq:type_name -> ua_mma.v1.StreamEventsRequest.LastSeenSeqEntry
	4, // 1: ua_mma.v1.UAEvent.emitted_at:type_name -> google.protobuf.Timestamp
	2, // 2: ua_mma.v1.UAEvent.entity_ref:type_name -> ua_mma.v1.EntityRef
	5, // 3: ua_mma.v1.UAEvent.payload:type_name -> google.protobuf.Struct
	0, // 4: ua_mma.v1.UAEventStreamService.StreamEvents:input_type -> ua_mma.v1.StreamEventsRequest
	1, // 5: ua_mma.v1.UAEventStreamService.StreamEvents:output_type -> ua_mma.v1.UAEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ua_mma_v1_event_stream_proto_init() }
func file_proto_ua_mma_v1_event_stream_proto_init() {
	if File_proto_ua_mma_v1_event_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ua_mma_v1_event_stream_proto_rawDesc), len(file_proto_ua_mma_v1_event_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ua_mma_v1_event_stream_proto_goTypes,
		DependencyIndexes: file_proto_ua_mma_v1_event_stream_proto_depIdxs,
		MessageInfos:      file_proto_ua_mma_v1_event_stream_proto_msgTypes,
	}.Build()
	File_proto_ua_mma_v1_event_stream_proto = out.File
	file_proto_ua_mma_v1_event_stream_proto_goTypes = nil
	file_proto_ua_mma_v1_event_stream_proto_depIdxs = nil
}
